### ISSUE TITLE
I found another one that dom.js can't parse

### ISSUE THREAD

**Issue by ndrswlkr** [mojolicious/dom.js#12]
here it is:
[cannot_parse.html.gz](https://github.com/mojolicious/dom.js/files/10324970/cannot_parse.html.gz)

**Comment by kraih** [comment]
Exact same issue as before. Regular expression needed a little tweaking for the V8 regex engine.

**Comment by ndrswlkr** [comment]
I'm really impressed on how quickly you fix these things!

Thank you for your great Work

Andreas

 
 

Gesendet: Samstag, 31. Dezember 2022 um 14:29 Uhr
Von: "Sebastian Riedel" ***@***.***>
An: "mojolicious/dom.js" ***@***.***>
Cc: "ndrs" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [mojolicious/dom.js] I found another one that dom.js can't parse (Issue #12)


 

Closed #12 as completed via a178beb.
