### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by touchsky2018** [mojolicious/dom.js#5]
node version:  v16.14.0

import DOM from '@mojojs/dom';

build error-----------------------------------------------------------

Did you mean './util'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (C:/Dev/09.source/frontend-electron/GSys, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }

@marcusramberg @kraih @jhthorsen @christopherraa

**Comment by kraih** [comment]
The CI tests show that it is actually working. So there must be something special about your node environment.

**Comment by kraih** [comment]
If i had to guess, i'd say you're mixing CJS and EJS? This module is EJS only, and that's intentional.

**Comment by kraih** [comment]
Assuming this has been resolved.
